# Generated by Django 5.0.7 on 2024-07-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionTask',
            fields=[
                ('function_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=200)),
                ('object_id', models.CharField(max_length=200)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('defined', 'ready to run'), ('scheduled', 'scheduled'), ('running', 'in progress'), ('requested_cancel', 'cancellation requested'), ('cancelled', 'cancelled'), ('successful', 'finished successfully'), ('unsuccessful', 'failed')], default='defined', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('log', models.TextField(blank=True, default='', null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
